export const AboutPeetamData = [
  {
    p1: "The parents of Sri Brahmasri Nemmikanti Narasaiah Acharyulu hailed from Allagadda village in Kurnool district, Andhra Pradesh. Their family belonged to a noble lineage deeply rooted in traditional sculpture (Silpakala) and operated a well-respected sculpture school, carrying forward the artistic legacy of the Viswakarma community. His grandfather was not only a master in goldsmithing but also an accomplished practitioner of Ayurveda. He was widely known for offering free medical services to people in surrounding villages. His profound knowledge of Nadi Pariksha (pulse diagnosis) was so refined that he could accurately diagnose and treat critical conditions. With his skill in Ayurveda, he even brought patients out of coma and restored life in individuals who were deemed beyond recovery.Despite the scarcity of essential herbs in the region, he resourcefully used locally available medicinal plants and prepared potent remedies.",
    p2: "Sri Brahmasri Nemmikanti Narasaiah Acharyulu’s grandfather belonged to a highly skilled lineage of traditional artisans, with five siblings, each mastering a unique craft—carpentry, blacksmithing, goldsmithing, gold sculpture, and stone sculpture. This diverse expertise reflected the rich heritage of the Viswakarma tradition, where each member contributed to preserving and passing on the ancient silpa shastra (science of arts and crafts).He himself had three sons, and with a vision of nurturing spiritual depth alongside practical skills, he enrolled his youngest son, Sri Janaardhanacharyulu, into a reputed Veda Paathashala in Tirupati, aspiring for him to become an expert in the Vedas. This decision highlighted the family’s commitment not just to material craftsmanship, but also to spiritual wisdom and dharmic living, ensuring the balance of art, service, and sacred knowledge across generations..",
    // p3: "During his early years, Sri Janaardhanacharyulu apprenticed under the renowned Ganapathi Sthapathi, one of the most respected figures in the field of temple architecture and sculpture, for a period of one year. Despite facing financial challenges, he sustained himself by taking up various minor jobs while continuing to pursue his passion for sculpture.With unwavering dedication, he eventually migrated to Ongole, where he established a traditional sculpture school. There, he not only passed on the ancient knowledge of Silpakala (sculptural art) but also nurtured a new generation of skilled artisans. Many of his students have gone on to achieve respectable positions and recognition in the field of sculpture, continuing the legacy of excellence and devotion that he so passionately",
    p3: "He was the only son of Sri Nemmikanti JanardhanaCharya and Srimati Siva Kumari. Raised in a family where art and spirituality coexisted harmoniously, he was exposed to both from an early age. Alongside his formal academic education, he developed a deep interest in spiritual practices, particularly in Chowdeswari Devi Upasana (devotional worship), which became a foundational aspect of his spiritual path. He also inherited and honed the art of sculpture, not merely as a craft, but as a sacred expression of devotion. This blend of artistic tradition and spiritual discipline laid the groundwork for his evolution into a revered Sadhguru, dedicated to the upliftment of others through knowledge, devotion, and service. ",
    // p5:"As time progressed, his spiritual inclination deepened, and he fully dedicated himself to Upasana (devotional worship) of divine forms such as Sri Chowdeswari Devi, Sri Lalita Parameswari, and Dakshina Kali. With intense sadhana and commitment, he also mastered the sacred sciences of Jyothishyam (Vedic astrology), Vastu Shastra (architectural energy principles), and Mantra Shastra (sacred chants and rituals).",
    p4:"In the course of his spiritual journey, Sri Brahmasri Nemmikanti Narasaiah Acharya deepened his knowledge by learning Tantrika Vidya (esoteric spiritual practices) under the guidance of   Brahmasri Kolakuri Ramakoteswararao Master Ji, a renowned master in the field. Under his mentorship, Acharya gained deeper insights into the mystical dimensions of spirituality, further enriching his sadhana and teachings.Beyond acquiring scriptural and spiritual wisdom, he also embraced the higher truth of loving and guiding disciples with compassion and understanding. He believed that a true guru not only imparts knowledge but also nurtures the spiritual and emotional well-being of each disciple, leading them with unconditional love, patience, and wisdom. ",
    p5:"Through this holistic approach—combining sacred knowledge, disciplined practice, and heartfelt guidance—Acharya became a beacon of light, inspiring generations of seekers to walk the path of devotion, self-realization, and service.",
  },
];
