export const AboutPeetamData = [

    {
        p1: "The Parents of Sri Brahmasri Nemmikanti Narasaiahcharyulu migrated from Allagadda village in Kurnool district of Andhra Pradesh. Their family used to run traditional sculpture school. His grandfather was an expert in Goldsmithing as well as in Ayurveda.  He used to do free service to people in surrounding villages and cure their health problems. His expertise in Nerve Knowledge is so precise, that he cured the patients who were in comma and those who were declared as almost dead, using his powerful Ayurveda knowledge. Eventhough the main herbs required were not available nearby, he collected the minimal herbs and plants surrounding the village and used them to cure thereby  giving a new lease of life to the those comma patients.",
        p2: "His Grandfather has 5 siblings and had 3 sons. Each of his siblings had their own skills in carpentery, blacksmithing, goldsmithing, gold sculpture and stone sculpture. Expecting to become expert in Vedas, he joined his last son Sri Janaardhanachary in Veda paathasala in Tirupati.",
        p3: "His Grandfather cured the member of family of Ahobilam Jeeyar swamy, who was in coma and gave him a life. Keeping this in mind the Jeeyar Swamy allowed his last son Sri Janaardhanachary into Veda Paathasala, eventhough the rules allowed only Vaidikas and Vaisthavas at that time. Later, Sri Janardhanachary discontinued from Veda Paathasaala and spent his time to learn the arts for a living.",
        p4: "During that period, Sri Janaardhanachary was an apprentice with Ganapathi Sthapathi for one year or so. For a living he was doing other minor works and migrated to Ongole and started traditional sculpture school and settled there. The students from this school are now in good positions with their skill in sculpture.",
        p5: "Sri Janaardhanachary was responsible in founding many schools in and around Ongole. He had one son who he named after his father, Sri Brahmasri Nemmikanti Narasaiahcharyulu, who studied till Intermediate and later he supported his father as sculptor. As a tradition passed on from forefathers, they have been continuing the Chowdeswari Peetam.",
        p6: "Sri Brahmasri Nemmikanti Narasaiahcharyulu has shown interest in both Chowdeswari Upasana as well as sculptor. As time passed, he fully pledged his time to upasana for dieties of Chowdeswari, Lalita Parameswari, Dhakshina Kali and mastered Jyothishyam, Vastu and Mantra Shastra, thereby giving suggestions and directions for the needy people along with his students and became a Sathguru.",
    }

]
